import React from "react";
// const itemPopular = [
//   "Canmore",
//   "Tucson",
//   "Anaheim",
//   "Benalmasdena",
//   "Jasper",
//   "Monterey",
//   "Marbella",
//   "Mountainview",
//   "Paso Robles",
//   "Mijas",
//   "Devonport",
//   "Santa Barbara",
//   "Prescott",
//   "Mallacoota",
//   "Sonoma",
//   "Scottsdale",
//   "Ibiza",
//   "Lasenrana",
//   "Padstow",
// ];
// const itemArtsCulture = [
//   "Phoenix",
//   "Prague",
//   "York",
//   "Hot Springs",
//   "Washington",
//   "Paris",
//   "Los Angeles",
//   "Keswick",
//   "Rhodes",
//   "San Diego",
//   "London",
//   "Nashvillee",
//   "San Francisco",
//   "Scarborough",
//   "Dublin",
//   "Barcelona",
//   "Shrwood Forest",
//   "South haven",
//   "Inverness",
// ];
// const itemOutdoors = [
//   "Lake Martin",
//   "North Rim",
//   "Emerald Lake",
//   "Banff",
//   "Payson",
//   "Vancouver Island",
//   "Nerja",
//   "Pinetop-Lakeside",
//   "Victoria",
//   "Greer",
//   "Red Rook",
//   "Idyllwild-Pine Cove",
//   "Lake Havasu City",
//   "Dinner Plain",
//   "Mammoth Lakes",
//   "Lake Powell",
//   "Stresky Bay",
//   "Palm Desert",
//   " Ottawa Eiver",
//   "Aspen",
// ];
// const itemMountian = [
//   "Mentone",
//   "Blue Mountain",
//   "Townsend",
//   "Sedona",
//   "Asheville",
//   "Wears Valley",
//   "Helen",
//   "Blowing Rock",
//   "Cabins",
//   "Pine Mountain",
//   "Boone",
//   "Stone Moutain",
//   "Hochatown",
//   "Island Park",
//   "Pigeon Forge",
// ];
// const itemBeach = [
//   "Dauphin Island",
//   "Hamilton Island",
//   "Big Sur",
//   "Fort Morgan",
//   "Lancelin",
//   "Bodega Bay",
//   "Gulf Shores",
//   "Melbourne Beach",
//   "Cambria",
//   "Bruny Island",
//   "Moonta Bay",
//   "Cayucos",
//   "Crescent Head",
//   "Ocean Grove",
//   "Huntington Beach",
//   "Gerringong",
//   "Majorca",
//   "la Jolla Shores Beach",
//   "Oceanside",
//   "Playa Blanca",
// ];
// const itemUniqueSatys = [
//   "Cabins",
//   "Lakehouses",
//   "Private Island Rentals",
//   "Treehouses",
//   "Yurt Rentals",
//   "Farm Houses",
//   "Glamping",
//   "Yurt Rentals",
//   "Farm Cottages",
//   "Tiny Houses",
//   "Castle Rentals",
//   "Cabin Rentals",
//   "Beach Houses",
//   "Houseboats",
//   "Luxury Cabins",
//   "Campers and RVs",
//   "Holiday Caravans",
//   "Luxury Cabins",
//   "Holiday Bungalows",
//   "Private Holiday Rentals",
// ];
// const itemCategories = [
//   "Amazing pools",
//   "Arctic",
//   "Camping",
//   "Campers",
//   "Castles",
//   "Containers",
//   "Countryside",
//   "Design",
//   "Earth homes",
//   "Farms",
//   "National parks",
//   "Vineyards",
//   "OMG!",
//   "Tiny homes",
//   "Towers",
//   " Windmills",
// ];
// const itemThing = [
//   "London",
//   "Amsterdam",
//   "Tokyo",
//   "Paris",
//   "Miami",
//   "Vienna",
//   "New York",
//   "Madrid",
//   "Athens",
//   "Barcelona",
//   "Los Angeles",
//   "Prague",
//   "İstanbul",
//   "Rome",
//   "Orlando",
//   "Bali",
//   "Lisbon",
//   "Cancún",
//   "Las Vegas",
//   "Atlanta",
//   "Denver",
// ];
// const itemAirbnb = [
//   "Palm Beach County",
//   "Dallas",
//   "Los Angeles",
//   "Atlanta Metro",
//   "Denver",
//   "Miami",
//   "Augusta",
//   "Gainesville",
//   "Minnetonka",
//   "Austin Metro",
//   "Houston Metro",
//   "Newport Beach",
//   "Boston Metro",
//   "Indianapolis",
//   "Marin County",
//   "Charlotte",
//   "Jacksonville",
//   "East Bay",
//   "Raleigh",
//   "San Jose",
// ];
const Getaways = (props) => {
  return (
    <div>
      <p>{props.value}</p>
    </div>
  );
};

export default Getaways;
